### ISSUE TITLE
多个账号的情况下, 可否将PUSHPLUS的通知合并为一条

### ISSUE THREAD

**Issue by FairyWorld** [yaoysyao/GLaDOS_Auto_Checkin#1]
多个账号的情况下, 可否将PUSHPLUS的通知合并为一条, 还有通知的标题可否改一下, 比如"galdos签到"之类的, 签到通知太多不容易区分

**Comment by yaoysyao** [comment]
标题比较好改，至于合并的问题，稍后我看一下

**Comment by FairyWorld** [comment]
> 标题比较好改，至于合并的问题，稍后我看一下

还有一个问题，action日志会显示出账号的名字，有点不合适

**Comment by yaoysyao** [comment]
> > 标题比较好改，至于合并的问题，稍后我看一下
> 
> 还有一个问题，action日志会显示出账号的名字，有点不合适

这个的话主要是考虑到多个账号可以方便的看出每个账号的签到信息，防止看不出哪个账号没成功，其实我也觉得有点不合适，打算去掉

**Comment by yaoysyao** [comment]
> 多个账号的情况下, 可否将PUSHPLUS的通知合并为一条, 还有通知的标题可否改一下, 比如"galdos签到"之类的, 签到通知太多不容易区分
1. 多个账号签到通知已合并
2. 工作流日志中不在输出邮箱账号，但是推送信息中依旧输出
请更新项目，并启动工作流进行验证
