### ISSUE TITLE
脚本失效了

### ISSUE THREAD

**Issue by FairyWorld** [yaoysyao/GLaDOS_Auto_Checkin#4]

**Comment by yaoysyao** [comment]
提示什么错误，为啥我看不到你的这个仓库？

**Comment by FairyWorld** [comment]
> 提示什么错误，为啥我看不到你的这个仓库？

刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费

**Comment by FairyWorld** [comment]
> 提示什么错误，为啥我看不到你的这个仓库？

如果是付费用户可能是正常的，我测试不了

**Comment by yaoysyao** [comment]
> > 提示什么错误，为啥我看不到你的这个仓库？
> 
> 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费

是不是这个错误，我的也是，免费用户不允许签到了
![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)

**Comment by FairyWorld** [comment]
> > > 提示什么错误，为啥我看不到你的这个仓库？
> > 
> > 
> > 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费
> 
> 是不是这个错误，我的也是，免费用户不允许签到了 ![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)

是的

**Comment by yaoysyao** [comment]
> > > > 提示什么错误，为啥我看不到你的这个仓库？
> > > 
> > > 
> > > 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费
> > 
> > 
> > 是不是这个错误，我的也是，免费用户不允许签到了 ![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)
> 
> 是的

改了规则了，不能白嫖了

**Comment by yaoysyao** [comment]
> > > > 提示什么错误，为啥我看不到你的这个仓库？
> > > 
> > > 
> > > 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费
> > 
> > 
> > 是不是这个错误，我的也是，免费用户不允许签到了 ![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)
> 
> 是的

我问了其他的付费用户，好像没啥事

**Comment by FairyWorld** [comment]
> > > > > 提示什么错误，为啥我看不到你的这个仓库？
> > > > 
> > > > 
> > > > 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费
> > > 
> > > 
> > > 是不是这个错误，我的也是，免费用户不允许签到了 ![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)
> > 
> > 
> > 是的
> 
> 我问了其他的付费用户，好像没啥事

签到送一天是不是随机概率？我之前忘记在哪里看到送不送1天看运气，如果稳定送一天，我想买个套餐，相当于永久了

**Comment by yaoysyao** [comment]
> > > > > > 提示什么错误，为啥我看不到你的这个仓库？
> > > > > 
> > > > > 
> > > > > 刚刚删除了，刚才发现glados改规则了，免费用户不允许签到，必须付费
> > > > 
> > > > 
> > > > 是不是这个错误，我的也是，免费用户不允许签到了 ![image](https://user-images.githubusercontent.com/38513384/178089719-4e419c60-3696-4b76-9201-e1ce96de86b2.png)
> > > 
> > > 
> > > 是的
> > 
> > 
> > 我问了其他的付费用户，好像没啥事
> 
> 签到送一天是不是随机概率？我之前忘记在哪里看到送不送1天看运气，如果稳定送一天，我想买个套餐，相当于永久了

并不是，签到超过30天的话，每次签到得到一天的概率好像是33%，就要看运气了，而且会员过期了，不知道还能不能签到，这我就不清楚了，你可以问问开通了会员的兄弟
