### ISSUE TITLE
报错力

### ISSUE THREAD

**Issue by linzi1014** [yaoysyao/GLaDOS_Auto_Checkin#6]
发生什么事了？突然就报错了，更新了cookie依旧
![VNVK}F}_I@8_Q6`SSL) P$N](https://user-images.githubusercontent.com/84072847/209890317-5f3e4188-8e50-4ba9-930d-ab3f5de32834.png)
![LAYEX$KH6484WX%OVPT %CG](https://user-images.githubusercontent.com/84072847/209890320-7b82789c-7d51-4e60-b56a-226c34527cfd.png)

**Comment by yaoysyao** [comment]
依赖包undetected-chromedriver升级，导致错误，在requirements.txt，指定版本undetected-chromedriver==3.1.7

**Comment by yaoysyao** [comment]
或者更新下代码，修改自己定义的时间就可以

**Comment by linzi1014** [comment]
已解决~
